### PR TITLE
replace quadMB

### PR DESCRIPTION
**Pull request by bennn**
cc @samth

This pull request:
- removes the `quadMB` benchmark
- renames the `quadBG` benchmark to `quadU` (U = from untyped)
- adds a `quadT` benchmark (T = from typed)

The new `quadT` starts with Matthew Butterick's typed code and:
- removes type annotations, 
- replaces `cast` with similar "asserts" (really, changing `(assert e p)` to `(contract p e '+ '-)`)
- replaces `define-predicate` functions with untyped functions

The current typed/untyped ratio is 2.83x, which is much "better" than `quadMB` but still a little high:

 benchmark | T ms | U ms | T/U 
--- | --- | --- | ---
 quadT | 5354 | 1889 | 2.83 
 quadMB | 5447 | 369 | 14.76 
quadBG | 3240 | 2530 | 1.28

(if `quadT` uses the `define-predicate` functions, then the untyped code takes ~6 seconds --- probably b/c of crossing a type boundary for every predicate call)

TODO
- [ ] explain the `quadT` typed/untyped ratio (it's probably `define-predicate` vs. predicates + contracts)
- [x] rebuild the scribble docs

### CODE REVIEW

**Comment by samth** [comment]
What are the numbers like for `quadU`? Why does the untyped code in quadT take so long?

Also, I'm confused about your comment about `assert`. The major cost of `cast` is that it translates to that `contract` form, so I don't see what's improved.

More generally, I think that we should first remove `quadMB`, and then if we can find a way to _fix_ the original typed code, we should add a benchmark based on that, but we shouldn't expect that to be guaranteed to work.

**Comment by bennn** [comment]
> What are the numbers like for quadU?

The quadU ratio is about 1.28 (quadU is exactly quadBG)

> Why does the untyped code in quadT take so long?

The untyped code in quadT is trying to do the same work as the typed code. (That was the problem with quadMB --- the typed and untyped code were doing different work.)

> Also, I'm confused about your comment about assert. The major cost of cast is that it translates to that contract form, so I don't see what's improved.

The point is: the typed code's `cast`s are something similar in untyped code, as opposed to being no-ops.

> More generally, I think that we should first remove quadMB, and then if we can find a way to fix the original typed code, we should add a benchmark based on that, but we shouldn't expect that to be guaranteed to work.

What do you mean, fix the typed code? I don't think there's anything to fix --- it's a working program written by someone who tried to improve a project with Typed Racket. The code may be inefficient in some ways, but its still meaningful to ask about the overhead of gradual typing (in this inefficient codebase).

**Comment by samth** [comment]
Do we know why the ratio for quadU is >1?

**Comment by bennn** [comment]
About the quadT ratio: I think the difference is due to my encoding of the `define-predicate`checks, but I'm not sure how to close the gap. For now I'd rather merge, make note of this (smaller) question, and remove quadMB (fixing a bigger issue).

- - -

For example, changing the definition of `QuadListItem?` (in `quadT/base/untyped-predicates.rkt`) from:

```(lambda (x) (or (string? x) (quad? x)))```

to

 ```(lambda (x) (contract-first-order-passes? (or/c string? quad?) x))```

increases the untyped running time to ~4000ms (see table above for comparison). But the latter is a bad definition because an `or/c` contract gets created each time the function is called.

It would be better to define all untyped predicates as contracts, but I haven't been able to untangle the recursive definitions. Here is one failed attempt:

```
(define-values [QuadAttrValue?  QuadAttr?  QuadAttrs?  QuadListItem?  QuadList?  quad?  quad-attrs?  GroupQuadListItem?  GroupQuadList?]
  (letrec
    ([quad?  (contract-first-order (list*/c QuadName? QuadAttrs? QuadList?))]
     [QuadAttrValue? (contract-first-order (or/c flonum? index? string? symbol? boolean? quad? QuadAttrs? QuadList? exact-integer?))]
     [QuadAttr? (contract-first-order (cons/c QuadAttrKey? QuadAttrValue?))]
     [QuadAttrs? (contract-first-order (listof QuadAttr?))]
     [QuadListItem?  (contract-first-order (or/c string? quad?))]
     [QuadList? (contract-first-order (listof QuadListItem?))]
     [quad-attrs? QuadAttrs?]
     [GroupQuadListItem? quad?]
     [GroupQuadList? (contract-first-order (listof GroupQuadListItem?))])
    (values QuadAttrValue?  QuadAttr?  QuadAttrs?  QuadListItem?  QuadList?  quad?  quad-attrs?  GroupQuadListItem?  GroupQuadList?)))
```

**Pull request merged**
